### ISSUE TITLE
Outdated ConnectionURL options documentated in pooled-jms-docs/Configuration.md

### ISSUE THREAD

**Issue by jdanekrh** [messaginghub/pooled-jms#11]
Configurations.md describes options `createConnectionOnStartup`, `expiryTimeout`, and `reconnectOnException`, which seem to have been removed or renamed.

Besides these, I figure , `timeBetweenExpirationCheckMillis` was renamed to `connectionCheckInterval`.
And  `maximumActiveSessionPerConnection` was renamed to `maxSessionsPerConnection`.

**Comment by tabish121** [comment]
I'm working on it
