### ISSUE TITLE
Leak in Session consumer tracking of closed pooled consumers

### ISSUE THREAD

**Issue by tabish121** [messaginghub/pooled-jms#22]
When a pooled consumer is closed the pooled session is removing the wrong reference from its internal tracking leading to a leak whereby it retains a reference to the closed pooled consumer wrapper.  The code needs to be tightened to avoid allowing this to happen and ensure that the pooled wrappers are removed properly.

**Comment by AntonRoskvist** [comment]
Hello @tabish121 
I cannot see this change getting applied to the 1.x-flavors... am I looking in the wrong place or are they simply not affected by the leak in the first place?

**Comment by AntonRoskvist** [comment]
Sounds good and I agree with you on leaving the old 1x-stuff. I'm just stuck with it through some old Spring dependencies for a little while longer, otherwise I'm using 2.x already. Thanks for getting back to me so fast!
