### ISSUE TITLE
Long running connections with failover do not work correctly

### ISSUE THREAD

**Issue by mkomadel** [messaginghub/pooled-jms#41]
We use pooled-jms in quarkus application with Artemis MQ jms client (https://docs.quarkiverse.io/quarkus-pooled-jms/dev/index.html).
Message receival is implemented with simple JMS message listeners. something along these lines:

```
connection = connectionFactory.createConnection() 
session = connection.createSession(Session.SESSION_TRANSACTED);
consumer = session.createConsumer(...)
consumer.setMessageListener(m -> onMessage(m));
```

Artemis MQ client connection string is setup to use failover (e.g. tcp://localhost:5672?amqbroker.reconnect.attempts=-1;...)
When using Artemis connection factory directly, everything works as expected, onn connection failure, reconnection is triggered an eventually the client is connected again and message listeners get incoming messages.

When using pooled-jms wrapper, listeners stop working after connection failure. According to my analysis, the problem is following:
ActiveMQConnection calls exception listener with connection exception (https://github.com/apache/activemq-artemis/blob/main/artemis-jms-client/src/main/java/org/apache/activemq/artemis/jms/client/ActiveMQConnection.java#L721), which I suppose is correct cause it came to connection disruption. But it tries to reconnect automatically and eventually succeeds. The problem is, that pooled-jms PooledConnection closes the underlying connection if any connection received. By closing the connection all sessions and listener are closed and no more messages are received.

Is there any possibility to mitigate this behaviour until this issue is (hopefully) fixed? like e.g. passing exception filter? Thanks

**Comment by tabish121** [comment]
The workaround is not to use automatic re-connection of the client if it is going to throw exceptions that indicate the connection has failed.  Other clients like Qpid JMS won't do this as the reconnection logic would first attempt to correct the situation.  The pool has no option but to react to a connection exception as a terminal outcome and close the connection

**Comment by mkomadel** [comment]
@tabish121 hi, thanks for the quick response. Not using the JMS client failover would force us to implement it in the application. I considered also other possible solution, getting the Artemis Connection Factory from JmsPoolConnectionFactory to create the long living connections and thus avoiding connection closure on reconnection. Is there any risc to this approach as far as pooled-jms is concerned ?

**Comment by tabish121** [comment]
I don't really understand what you are asking so I can't really comment one way or the other.

**Comment by mkomadel** [comment]
@tabish121 sorry, I'll try to rephrase it. The idea is to get the 
```ConnectionFactory used to create the pooled Connections``` using the ```JmsPoolConnectionFactory.getConnectionFactory()``` method, which would give me ```ActiveMQConnectionFactory ```. We would create the long living connections using ```ActiveMQConnectionFactory ``` instead of  ```JmsPoolConnectionFactory```, which avoids the above mentioned problems by failover. 
The question is, if this approach can break connection pooling or lead to memory leaks in pooled-jms? (I doesn't look like it at first glance but I'd like to be sure) Thanks.

**Comment by tabish121** [comment]
I wouldn't think there would be any issue with sharing the connection factory, the best answer would come from tests though. Most ConnectionFactory implementations are simple and don't have any significant state sharing from factory to connections.
